### ISSUE TITLE
What is the difference with https://github.com/patractlabs/redspot

### ISSUE THREAD

**Issue by charkali** [patractlabs/redspot#7]

**Comment by atenjin** [comment]
https://github.com/patractlabs/redspot is our first version to do a minimum MVP verification for establishing a framework for contract developing.
Then we think the framework for repo https://github.com/patractlabs/redspot is not suit for future requirement, so we decide to use a new framework which is forked from buidler for RedSpot. We name it RedSpot-0.2 just now.
For RedSpot-0.2 is under developing and can't be used now, so we could not name `RedSpot-0.2` to `RedSpot`.
After RedSpot-0.2 release, we would change old repo https://github.com/patractlabs/redspot to `RedSpot-archived` and change this repo name from `redspot-0.2` to `redspot`.
So that the old repo https://github.com/patractlabs/redspot would be replaced after this repo redspot-0.2 be released first version.

**Comment by ii-ii-ii** [comment]
@charkali  We've launched a new version of RedSpot that you might be interested in trying out. https://patractlabs.github.io/redspot/
